AllCops:
  EnabledByDefault: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/Copyright:
  Enabled: false